src/Entity/Vehicles.php
<?php

namespace App\Entity;

use App\Repository\VehiclesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiclesRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Vehicles
{
    #[ORM\Id]
    #[ORM\GeneratedValue('CUSTOM')]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\CustomIdGenerator('doctrine.uuid_generator')]
    private ?string $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    private ?string $brandName = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    private ?string $type = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    private ?string $model = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $releaseDate = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2, nullable: true)]

    private ?string $price = null;

    #[ORM\Column(length: 255)]
    private ?string $featured_image = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero()]
    private ?int $mileage = null;

    #[ORM\Column]
    #[Assert\PositiveOrZero()]
    private ?int $fiscal_power = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero()]
    private ?int $power = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $motorization = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 4, scale: 1, nullable: true)]
    #[Assert\PositiveOrZero()]
    private ?string $consumption = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero()]
    private ?int $emission_rate = null;

    #[ORM\Column(length: 1, nullable: true)]
    private ?string $energy_class = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $color = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero()]
    private ?int $length = null;

    #[ORM\Column(nullable: true)]
    private ?int $width = null;

    #[ORM\Column(nullable: true)]
    private ?int $height = null;

    #[ORM\Column(nullable: true)]
    private ?int $unloaded_weight = null;

    #[ORM\Column(nullable: true)]
    private ?int $total_weight = null;

    #[ORM\Column(nullable: true)]
    private ?int $max_speed = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero()]
    private ?int $number_of_doors = null;


    #[ORM\PrePersist]
    public function prePersist()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    #[ORM\PreUpdate]
    public function preUpdate()
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getBrandName(): ?string
    {
        return $this->brandName;
    }

    public function setBrandName(string $brandName): static
    {
        $this->brandName = $brandName;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeImmutable
    {
        return $this->releaseDate;
    }

    public function setReleaseDate(\DateTimeImmutable $releaseDate): static
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    public function setMileage(?int $mileage): static
    {
        $this->mileage = $mileage;

        return $this;
    }

    public function getFiscalPower(): ?int
    {
        return $this->fiscal_power;
    }

    public function setFiscalPower(int $fiscal_power): static
    {
        $this->fiscal_power = $fiscal_power;

        return $this;
    }

    public function getPower(): ?int
    {
        return $this->power;
    }

    public function setPower(?int $power): static
    {
        $this->power = $power;

        return $this;
    }

    public function getMotorization(): ?string
    {
        return $this->motorization;
    }

    public function setMotorization(?string $motorization): static
    {
        $this->motorization = $motorization;

        return $this;
    }

    public function getConsumption(): ?string
    {
        return $this->consumption;
    }

    public function setConsumption(?string $consumption): static
    {
        $this->consumption = $consumption;

        return $this;
    }

    public function getEmissionRate(): ?int
    {
        return $this->emission_rate;
    }

    public function setEmissionRate(?int $emission_rate): static
    {
        $this->emission_rate = $emission_rate;

        return $this;
    }

    public function getEnergyClass(): ?string
    {
        return $this->energy_class;
    }

    public function setEnergyClass(?string $energy_class): static
    {
        $this->energy_class = $energy_class;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function getLength(): ?int
    {
        return $this->length;
    }

    public function setLength(?int $length): static
    {
        $this->length = $length;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(?int $width): static
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(?int $height): static
    {
        $this->height = $height;

        return $this;
    }

    public function getUnloadedWeight(): ?int
    {
        return $this->unloaded_weight;
    }

    public function setUnloadedWeight(?int $unloaded_weight): static
    {
        $this->unloaded_weight = $unloaded_weight;

        return $this;
    }

    public function getTotalWeight(): ?int
    {
        return $this->total_weight;
    }

    public function setTotalWeight(?int $total_weight): static
    {
        $this->total_weight = $total_weight;

        return $this;
    }

    public function getMaxSpeed(): ?int
    {
        return $this->max_speed;
    }

    public function setMaxSpeed(?int $max_speed): static
    {
        $this->max_speed = $max_speed;

        return $this;
    }

    public function getNumberOfDoors(): ?int
    {
        return $this->number_of_doors;
    }

    public function setNumberOfDoors(?int $number_of_doors): static
    {
        $this->number_of_doors = $number_of_doors;

        return $this;
    }
}

src/Controller/Admin/VehiclesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Vehicle;
use App\Form\VehiclesType;
use App\Repository\VehiclesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('admin/vehicles', name: 'admin_vehicles_')]
class VehiclesController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(VehiclesRepository $vehiclesRepository): Response
    {

        $vehicles = $vehiclesRepository->findAll();
        return $this->render('admin/vehicles/index.html.twig', [
            'page_title' => 'Vos véhicules d\'occasion',
            'vehicles' => $vehicles
        ]);
    }


    #[Route('/new', name: 'new')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        $vehicle = new Vehicle();
        $form = $this->createForm(VehiclesType::class, $vehicle);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($vehicle);
            $entityManager->flush();
            $this->addFlash('success', 'Véhicule bien enregistré');

            return $this->redirectToRoute('admin_vehicles_index', [], Response::HTTP_SEE_OTHER);
        }


        return $this->render('admin/vehicles/new.html.twig', [
            'page_title' => 'Ajouter un nouveau véhicule',
            'form' => $form
        ]);
    }

    #[Route('/edit/{id}', name: 'edit')]
    public function edit(Request $request, EntityManagerInterface $entityManager, Vehicle $vehicle): Response
    {

        $form = $this->createForm(VehiclesType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admin_vehicles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/vehicles/edit.html.twig', [
            'page_title' => 'Editer un véhicule',
            'form' => $form
        ]);
    }
}

src/Controller/VehiclesController.php
<?php

namespace App\Controller;

use App\Entity\Vehicle;
use App\Form\SearchType;
use App\Model\SearchDTO;
use App\Repository\VehiclesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\Attribute\MapRequestPayload;

#[Route('/vehicles', name: 'vehicles_')]
class VehiclesController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(

        Request $request,
        VehiclesRepository $vehiclesRepository,
        FormFactoryInterface $formFactory
    ): Response {
        $formSearch = $formFactory->createNamed('', SearchType::class, null, [
            'method' => 'POST'
        ]);

        return $this->render('vehicles/index.html.twig', [
            'pageTitle' => 'Véhicules d\'occasions',
            'vehicles' => $vehiclesRepository->findAll(),
            'formSearch' => $formSearch
        ]);
    }

    #[Route('/{id}/view', name: 'view')]
    public function view(Vehicle $vehicle): Response
    {

        return $this->render('vehicles/view.html.twig', [
            'vehicle' => $vehicle
        ]);
    }

    #[Route('/filter', name: 'filter')]
    public function filteredVehicles(
        Request $request,
        VehiclesRepository $vehiclesRepository
    ) {

        $payload = $request->getPayload();

        $filters = [];
        foreach ($payload as $key => $value) {
            $filters[$key] = $value;
        }
        $vehicles = $vehiclesRepository->findVehiclesFiltered($filters);

        return $this->json($vehicles);
    }
}

templates/vehicles/_card.html.twig
<div class="card border-0 h-100">
	{% if vehicle.featuredImage %}
		{# <img src="{{ vich_uploader_asset(vehicle) }}" class="card-img-top img-fluid" alt="{{vehicle.title}}"> #}

		<img src="{{ asset('uploads/images/default.png') }}" class="card-img-top img-fluid" alt="{{vehicle.brandName}}"/>
	{% else %}
		<img src="{{ asset('uploads/images/default.png') }}" class="card-img-top img-fluid" alt="{{vehicle.brandName}}"/>
	{% endif %}
	{# <img src="{{ asset('uploads/images/default.png') }}" class="card-img-top img-fluid" alt="{{vehicle.brandName}}"> #}
	{# <img src="{{ vich_uploader_asset(vehicle) }}" class="card-img-top img-fluid" alt="{{vehicle.brandName}}"> #}
	<div class="card-body">
		<h2 class="card-title">{{ vehicle.brandName }}
			{{ vehicle.model }}</h2>
		<div>
			<div class="d-flex">
				<div class="fw-bold w-50">Price</div>
				<div>{{ vehicle.price }}
					€ TTC</div>
			</div>
			<div class="d-flex">
				<div class="fw-bold w-50">Kilométrage</div>
				<div>{{ vehicle.mileage}}
					kms</div>
			</div>
			<div class="d-flex">
				<div class="fw-bold w-50">Année</div>
				<div>{{ vehicle.releaseDate|date('Y', timezone="Europe/Paris")}}</div>
			</div>
		</div>
	</div>
	<div class="card-footer bg-transparent text-end border-0">
		<a href="{{ path('vehicles_view', {'id': vehicle.id}) }}" class="btn btn-primary">Détails</a>
	</div>
</div>

templates/vehicles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Véhicules d'occasions
{% endblock %}

{% block body %}
	<h1>{{ pageTitle }}</h1>
	{% form_theme formSearch 'bootstrap_5_layout.html.twig' %}
	{{ form_start(formSearch, {'attr' : {'id':'formVehicleFilters'}}) }}
	<div class="row">

		<div class="col">
			{{form_row (formSearch.minPrice)}}
		</div>

		<div class="col">
			{{form_row (formSearch.maxPrice)}}
		</div>

		<div class="col">
			{{form_row (formSearch.minMileage)}}
		</div>
		<div class="col">
			{{form_row (formSearch.maxMileage)}}
		</div>
		<div class="col-auto">
			<button class="btn btn-sm btn-primary" id="btnSearch">Filtrer</button>
		</div>
	</div>
	{{ form_end(formSearch) }}
	<div class="row row-cols-1 row-cols-md-3 g-4 js-vehicles">
		{% for vehicle in vehicles %}
			{% include "./vehicles/_card.html.twig" %}
		{% endfor %}
	</div>
{% endblock %}
{% block javascripts %}

	{# <script src="https://unpkg.com/axios/dist/axios.min.js"></script> #}
	<script src="{{ asset('js/vehicle-filter.js') }}"></script>

	{# <script>
		window.addEventListener('load', function (event) {
		document.querySelector('#btnSearch').addEventListener('click', vehiclesFilter)
		})
		
		function vehiclesFilter(e) {
		e.preventDefault()
		const formFilter = document.getElementById('formVehicleFilters')
		const data = new FormData(formFilter)
		const headers = {
		'Content-Type': 'application/json'
		}
		
		const body = {}
		for (const [key, value] of data) {
		body[key] = value
		}
		
		// console.log(body)
		const test = fetch(formFilter.action + 'filter/list', {
		method: 'POST',
		headers,
		body: JSON.stringify(body)
		}).then((res) => res.json()).then((vehicles) => {
		const vehiclesWrapper = document.querySelector('.js-vehicles')
		vehiclesWrapper.innerHTML = ''
		let html = ''
		for (const vehicle of vehicles) {
		console.log(vehicle)
		html += `<div class="card border-0 h-100">`
		html += `<img src="/uploads/images/default.png') }}" class="card-img-top img-fluid" alt="${
		vehicle.title
		}">`
		html += `<div class="card-body">`
		html += `<h2> ${
		vehicle.brandName
		} ${
		vehicle.model
		}</h2>`
		html += `<p class="card-text"> ${
		vehicle.price
		} </p>`
		
		html += `<div class="row row-cols-2">`
		html += `<div class="col">Puiss. :${
		vehicle.power
		} kW (${
		vehicle.fiscalPower
		} ch )</div>`
		html += `<div class="col">Année :${
		vehicle.releaseDate
		}</div>`
		html += `<div class="col">Moteur :${
		vehicle.motorization
		} (${
		vehicle.engineDisplacement
		} cm3)</div>`
		html += `<div class="col">Kilométrage :${
		vehicle.mileage
		} </div>`
		
		html += `</div>`
		html += `<a href="{{ path('vehicles_view', {'id':  ${
		vehicle.id
		}  }) }}" class="btn btn-primary">Détails</a>`
		html += `</div>`
		html += `</div>`
		vehiclesWrapper.innerHTML += html
		html = ''
		}
		}).catch(function (error) { // en cas d’échec de la requête
		console.log(error)
		})
		}
		</script> #}
{% endblock %}

templates/vehicles/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
	<a href="{{ path('vehicles_index') }}">Retour</a>
	<h1>{{ vehicle.brandName }}
		{{ vehicle.model}}</h1>
	<div class="row">
		<div class="col">
			<img
			src="{{ vich_uploader_asset(vehicle) }}" class="card-img-top img-fluid" alt="{{vehicle.brandName}}">

			{# <img src="{{ asset('uploads/images/default.png') }}" class="card-img-top img-fluid" alt="{{vehicle.brandName}}"></div> #}
			<div class="col">
				<div>
					<div>Véhicule ajouté le{{vehicle.createdAt|date('d/m/Y', timezone="Europe/Paris") }}</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Price</div>
						<div>{{ vehicle.price }}
							€ TTC</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Kilométrage</div>
						<div>{{ vehicle.mileage}}
							kms</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Année</div>
						<div>{{ vehicle.releaseDate|date('Y', timezone="Europe/Paris")}}</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Année</div>
						<div>{{ vehicle.releaseDate|date('Y', timezone="Europe/Paris")}}</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Puiss. :

						</div>
						<div>
							{{ vehicle.power }}
							kW ({{ vehicle.fiscalPower}}
							ch)
						</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Moteur :</div>
						<div>
							{{ vehicle.motorization}}
							(
							{{vehicle.engineDisplacement}}
							) cm3</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">
							Conso :</div>
						<div>
							{{ vehicle.consumption}}
							l/100km</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Vitesse max. :</div>
						<div>{{vehicle.maxSpeed}}</div>
					</div>
					<div class="d-flex">
						<div class="fw-bold w-50">Portes :</div>
						<div>{{ vehicle.numberOfDoors}}
						</div>
					</div>
				</div>

			</div>
			<div class="col">
				<div class="d-flex">
					<div class="fw-bold w-50">Equipements :</div>
					<div>{{ vehicle.numberOfDoors}}
					</div>
				</div>
				<div class="d-flex">
					<div class="fw-bold w-50">Options :</div>
					<div>{{ vehicle.numberOfDoors}}
					</div>
				</div>
			</div>
		</div>
	{% endblock %}